### ISSUE TITLE
패키지 보안 취약점 발생 

### ISSUE THREAD

**Issue by future9061** [team-3-in/toeic#26]
## 버그에 대한 설명

- Inefficient Regular Expression Complexity in nth-check 
- PostCSS line return parsing error 

## 재현 방법

어떤 식으로 발생했는지 순서대로 작성해주세요:

1. 깃 허브 보안 취약점 알림 발생으로 알게 된 에러

## 스크린샷

해당하는 경우 스크린샷을 추가하여 문제를 설명.

## 추가 내용

여기에 문제에 대한 다른 내용을 추가합니다.

**Comment by Zamoca42** [comment]
보안 취약점 원인인 react-scripts를 제거했습니다.
